name: "Issue Autolink"
on:
    pull_request:
        types: [opened]

jobs:
    issue-links:
        runs-on: ubuntu-latest
        steps:
            - uses: tkt-actions/add-issue-links@v1.8.1
              with:
                  repo-token: "${{ secrets.PEBBLE_TOKEN }}"
                  resolve: "true"